import type { TypedFlatConfigItem } from '@antfu/eslint-config'

type Rules = TypedFlatConfigItem['rules']

export const typescriptOverrides: Rules = {
	'ts/consistent-type-assertions': ['warn', { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' }],
	'ts/explicit-function-return-type': ['warn', {
		allowExpressions: true,
		allowHigherOrderFunctions: true,
		allowConciseArrowFunctionExpressionsStartingWithVoid: true,
	}],
	'ts/explicit-member-accessibility': ['warn', { accessibility: 'explicit', overrides: { constructors: 'no-public' } }],
	'ts/method-signature-style': ['error', 'property'],
	'ts/no-confusing-non-null-assertion': 'error',
	'ts/no-dynamic-delete': 'error',
	'ts/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
	'ts/no-explicit-any': 'warn',
	'ts/no-extra-non-null-assertion': 'error',
	'ts/no-import-type-side-effects': 'error',
	'ts/no-invalid-this': 'error',
	'ts/no-invalid-void-type': 'warn',
	'ts/no-non-null-assertion': 'warn',
	'ts/no-unsafe-declaration-merging': 'error',
	'ts/no-unsafe-function-type': 'error',
	'ts/no-use-before-define': ['error', { functions: false, classes: false, variables: true, typedefs: false }],
	'ts/no-wrapper-object-types': 'error',
	'ts/prefer-for-of': 'warn',
	'ts/prefer-namespace-keyword': 'error',
	'ts/prefer-optional-chain': 'warn',
	'ts/triple-slash-reference': 'error',
}

export const typescriptTypeAwareOverrides: Rules = {
	'e18e/prefer-includes': 'off',
	'ts/no-redundant-type-constituents': 'off',
	'ts/strict-boolean-expressions': 'off',
	'ts/naming-convention': [
		'warn',
		{ selector: 'default', format: ['camelCase'], leadingUnderscore: 'allow', trailingUnderscore: 'allow' },
		{ selector: 'variable', format: ['camelCase', 'UPPER_CASE'], leadingUnderscore: 'allow', trailingUnderscore: 'allow' },
		{ selector: 'variable', types: ['boolean'], format: ['camelCase', 'PascalCase'], prefix: [
			'is',
			'are',
			'was',
			'were',
			'has',
			'have',
			'had',
			'should',
			'would',
			'could',
			'will',
			'did',
			'does',
			'do',
			'can',
			'could',
			'may',
			'might',
			'exists',
			'contains',
			'includes',
			'supports',
			'needs',
			'requires',
			'show',
			'hide',
			'visible',
			'hidden',
			'collapsed',
			'expanded',
			'ready',
			'done',
			'pending',
			'loading',
			'active',
			'enabled',
			'disabled',
			'checked',
			'selected',
		] },
		{ selector: 'variable', types: ['function'], format: ['camelCase', 'PascalCase'] },
		{ selector: 'parameter', format: ['camelCase'], leadingUnderscore: 'allow' },
		{ selector: 'function', format: ['camelCase', 'PascalCase'] },
		{ selector: 'memberLike', format: ['camelCase'], leadingUnderscore: 'allow' },
		{ selector: 'memberLike', modifiers: ['private', 'protected'], format: ['camelCase'], leadingUnderscore: 'require' },
		{ selector: 'classProperty', modifiers: ['static'], format: ['camelCase'], leadingUnderscore: 'allow' },
		{ selector: 'classProperty', modifiers: ['private', 'protected', 'static'], format: ['camelCase'], leadingUnderscore: 'require' },
		{ selector: 'enum', format: ['UPPER_CASE', 'PascalCase'] },
		{ selector: 'enumMember', format: ['UPPER_CASE', 'PascalCase'] },
		{ selector: 'typeLike', format: ['PascalCase'] },
		{ selector: 'typeParameter', format: ['PascalCase'] },
		{ selector: 'objectLiteralProperty', format: null, modifiers: ['requiresQuotes'] },
	],
	'ts/no-base-to-string': 'warn',
	'ts/no-meaningless-void-operator': 'error',
	'ts/no-unnecessary-boolean-literal-compare': 'error',
	'ts/no-unnecessary-condition': 'warn',
	'ts/no-unnecessary-type-arguments': 'error',
	'ts/non-nullable-type-assertion-style': 'error',
	'ts/only-throw-error': 'error',
	'ts/prefer-includes': 'error',
	'ts/prefer-nullish-coalescing': ['error', { ignorePrimitives: true }],
	'ts/prefer-readonly': 'error',
	'ts/prefer-regexp-exec': 'warn',
	'ts/prefer-string-starts-ends-with': 'error',
	'ts/return-await': ['error', 'always'],
	'ts/require-array-sort-compare': 'error',
	'ts/switch-exhaustiveness-check': ['error', {
		allowDefaultCaseForExhaustiveSwitch: true,
		considerDefaultExhaustiveForUnions: true,
	}],
}
